set -g default-terminal "screen-256color"

set -g history-limit 9999999

#set -g status-bg  
#set -g status-fg 


set -g prefix C-s
bind C-s send-prefix
unbind C-b

set -g mouse on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file 
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

#setw -g clock-mode-colour magenta

# start windows and panes with index 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# keep current path on the new window
bind c new-window -c "#{pane_current_path}"

# join pane from another window into a different window
bind j choose-window 'join-pane -h -s "%%"' # horizontally
bind J choose-window 'join-pane -s "%%"' # vertically
